require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'spec/spec_helper.rb'
    - 'config/environments/production.rb'
    - 'config/puma.rb'

Metrics/BlockLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/FirstArrayElementIndentation:
  Exclude:
    - 'spec/api/warehouse/products_spec.rb'
    - 'spec/models/product_spec.rb'

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  Exclude:
    - 'spec/api/warehouse/products_spec.rb'
    - 'spec/models/product_spec.rb'
